### PR TITLE
Fixes post-provisioning instructions for Rock Pi 4B

### PR DESCRIPTION
**Pull request by Bucknalla**
Change-type: patch
Signed-off-by: Alex Bucknall <alex.bucknall@gmail.com>

### CODE REVIEW

**Review by floion — APPROVED** [review]

**Comment by floion** [comment]
@resin-jenkins test this please

**Comment by rcooke-warwick** [comment]
this PR will not pass tests until https://github.com/balena-os/balena-radxa/pull/258 is merged

**Comment by Bucknalla** [comment]
@balena-ci rebase

**Comment by rcooke-warwick** [comment]
@resin-jenkins test this please

**Comment by rcooke-warwick** [comment]
@balena-ci rebase

**Comment by rcooke-warwick** [comment]
@resin-jenkins retest this please

**Comment by Bucknalla** [comment]
@resin-jenkins retest this please

**Comment by rcooke-warwick** [comment]
@resin-jenkins retest this please

**Comment by klutchell** [comment]
@resin-jenkins ok to test

**Pull request merged**
